import 'package:flutter/material.dart';

class Localization {
  Localization(this.locale);

  final Locale locale;

  static Localization of(BuildContext context) {
    return Localizations.of<Localization>(context, Localization);
  }

  static Map<String, Map> _localizedValues = {
    'en': {
      'language': ['Language'],
      'search': ['Search', 'Empty search query .. start type one'],
      'profile': ['Profile', 'Language', 'Log out'],
      'auth': [
        'Login',
        'Sign up',
        'Create new account',
        'Forget password',
        'First name',
        'Last name',
        'Email',
        'Password',
        'Repeat password',
        'This Field is required',
        'Invalid email Address',
        'Password must be equal or greater than 8 letters',
        'Password not identical',
        'Reset your password',
        'Problem in our server we art working on fix it',
        'Problem in your network connection .. please check it',
        'Recheck your Email and password',
        'Recheck your Email',
        'Email address is Already Taken'
      ],
      'filter': [
        'Filters',
        'Cities',
        'Features',
        'Price',
        'Price Range',
        'Filters',
        'Clear Filter'
      ],
      'book': [
        'Book This Tour',
        'Tour',
        'Date',
        'Passengers',
        'Booking',
        'Passenger',
        'Done',
        'Cancel',
        'Clear',
        'Adults',
        'Children',
        'Infants',
        'under',
        'year',
        'Must select date and passengers',
        'Something went wrong try again',
        'Booking is successfully done',
        'Select Date'
      ],
      'info': ['Booking'],
      'countries': [
        'Afghanistan',
        'Albania',
        'Algeria',
        'American Samoa',
        'Andorra',
        'Angola',
        'Anguilla',
        'Antigua and Barbuda',
        'Argentina',
        'Armenia',
        'Aruba',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Belize',
        'Benin',
        'Bermuda',
        'Bhutan',
        'Bolivia',
        'Bosnia and Herzegovina',
        'Botswana',
        'Brazil',
        'British Indian Ocean Territory',
        'British Virgin Islands',
        'Brunei Darussalam',
        'Bulgaria',
        'Burkina Faso',
        'Burundi',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Cape Verde',
        'Cayman Islands',
        'Central African Rep',
        'Chad',
        'Chile',
        'China',
        'Christmas Island',
        'Cocos (Keeling) Islands',
        'Colombia',
        'Comoros',
        'Congo, Democratic Rep of',
        'Congo, Republic of',
        'Cook Islands',
        'Costa Rica',
        "Cote d'Ivoire",
        'Croatia',
        'Cuba',
        'Cyprus',
        'Czech Rep',
        'Denmark',
        'Djibouti',
        'Dominica',
        'Dominican Rep',
        'Ecuador',
        'Egypt',
        'El Salvador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        'Ethiopia',
        'Falkland Islands',
        'Faroe Islands',
        'Fiji',
        'Finland',
        'France',
        'French Guyana',
        'French Polynesia',
        'Gabon',
        'Gambia',
        'Georgia',
        'Germany',
        'Ghana',
        'Gibraltar',
        'Greece',
        'Greenland',
        'Grenada',
        'Guadeloupe',
        'Guam',
        'Guatemala',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Honduras',
        'Hong Kong',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Italy',
        'Jamaica',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        'Korea, North',
        'Korea, South',
        'Kuwait',
        'Kyrgyzstan',
        'Laos',
        'Latvia',
        'Lebanon',
        'Lesotho',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Macau',
        'Macedonia',
        'Madagascar',
        'Malawi',
        'Malaysia',
        'Maldives',
        'Mali',
        'Malta',
        'Marshall Islands',
        'Martinique',
        'Mauritania',
        'Mauritius',
        'Mayotte',
        'Mexico',
        'Micronesia',
        'Moldova, Rep of',
        'Monaco',
        'Mongolia',
        'Montenegro',
        'Montserrat',
        'Morocco',
        'Mozambique',
        'Myanmar',
        'Namibia',
        'Nauru',
        'Nepal',
        'Netherlands',
        'Netherlands Antilles',
        'New Caledonia',
        'New Zealand',
        'Nicaragua',
        'Niger',
        'Nigeria',
        'Niue',
        'Norfolk Island',
        'Northern Mariana Islands',
        'Norway',
        'Oman',
        'Pakistan',
        'Palau',
        'Palestinian Territory, Occupied',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines',
        'Pitcairn Islands',
        'Poland',
        'Portugal',
        'Puerto Rico',
        'Qatar',
        'Reunion',
        'Romania',
        'Russian Federation',
        'Rwanda',
        'Samoa',
        'San Marino',
        'Sao Tome and Principe',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Sierra Leone',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'Solomon Islands',
        'Somalia',
        'South Africa',
        'Spain',
        'Sri Lanka',
        'St Helena',
        'St Kitts and Nevis',
        'St Lucia',
        'St Pierre and Miquelon',
        'St Vincent and Grenadines',
        'Sudan',
        'Suriname',
        'Swaziland',
        'Sweden',
        'Switzerland',
        'Syria',
        'Taiwan, Rep of China',
        'Tajikistan',
        'Tanzania',
        'Thailand',
        'Timor-Leste',
        'Togo',
        'Tokelau',
        'Tonga',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Turkmenistan',
        'Turks and Caicos Islands',
        'Tuvalu',
        'Uganda',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'United States of America',
        'United States Virgin Islands',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Vatican City',
        'Venezuela',
        'Viet Nam',
        'Wallis and Futuna Islands',
        'Western Sahara',
        'Yemen',
        'Zambia',
        'Zimbabwe'
      ],
      'checkOut': [
        'Check Out',
        'Credit Card Details',
        'First Name',
        'Sur Name',
        'Billing Information',
        'Street Address',
        'City',
        'Post Code',
        'Country',
        'Contact Details',
        'Email',
        'Pay Now',
        'Region',
        'You should fill all Fields'
      ],
      'globals': ['Wait for loading ..'],
      'more': ['More', 'Less', 'View on map'],
    },
    'ar': {
      'countries': [
        'أفغانستان',
        'ألبانيا',
        'الجزائر',
        'ساموا الأمريكية',
        'أندورا',
        'أنغولا',
        'أنغيلا',
        'أنتيغوا وبربودا',
        'الأرجنتين',
        'أرمينيا',
        'أروبا',
        'أستراليا',
        'النمسا',
        'أذربيجان',
        'جزر البهاما',
        'البحرين',
        'بنغلاديش',
        'بربادوس',
        'روسيا البيضاء',
        'بلجيكا',
        'بليز',
        'بنين',
        'برمودا',
        'بوتان',
        'بوليفيا',
        'البوسنة والهرسك',
        'بوتسوانا',
        'البرازيل',
        'إقليم المحيط البريطاني الهندي',
        'جزر فيرجن البريطانية',
        'بروناي دار السلام',
        'بلغاريا',
        'بوركينا فاسو',
        'بوروندي',
        'كمبوديا',
        'الكاميرون',
        'كندا',
        'الرأس الأخضر',
        'جزر كايمان',
        'جمهورية إفريقيا الوسطى',
        'تشاد',
        'تشيلي',
        'الصين',
        'جزيرة الكريسماس',
        'جزر كوكوس (كيلنج)',
        'كولومبيا',
        'جزر القمر',
        'جمهورية الكونغو الديمقراطية',
        'جمهورية الكونغو',
        'جزر كوك',
        'كوستا ريكا',
        'ساحل العاج',
        'كرواتيا',
        'كوبا',
        'قبرص',
        'جمهورية التشيك',
        'الدنمارك',
        'جيبوتي',
        'دومينيكا',
        'جمهورية الدومينيكان',
        'إكوادور',
        'مصر',
        'السلفادور',
        'غينيا الإستوائية',
        'إريتريا',
        'إستونيا',
        'أثيوبيا',
        'جزر فوكلاند',
        'جزر فاروس',
        'فيجي',
        'فنلندا',
        'فرنسا',
        'غيانا الفرنسية',
        'بولينيزيا الفرنسية',
        'الغابون',
        'غامبيا',
        'جورجيا',
        'ألمانيا',
        'غانا',
        'جبل طارق',
        'اليونان',
        'الأرض الخضراء',
        'غرينادا',
        '	غواديلوب',
        'غوام',
        'غواتيمالا',
        'غينيا',
        '	غينيا - بيساو',
        'غيانا',
        'هايتي',
        'هندوراس',
        'هونج كونج',
        'هنغاريا',
        'أيسلندا',
        'الهند',
        'إندونيسيا',
        'إيران',
        'العراق',
        'أيرلندا',
        'إيطاليا',
        'جامايكا',
        'اليابان',
        'الأردن',
        'كازاخستان',
        'كينيا',
        'كيريباتي',
        'كوريا الشمالية',
        'كوريا، جنوب',
        'الكويت',
        'قيرغيزستان',
        'لاوس',
        'لاتفيا',
        'لبنان',
        'ليسوتو',
        'ليبيريا',
        'ليبيا',
        'ليختنشتاين',
        'ليتوانيا',
        'لوكسمبورج',
        'ماكاو',
        'مقدونيا',
        'مدغشقر',
        'ملاوي',
        'ماليزيا',
        'جزر المالديف',
        'مالي',
        'مالطا',
        'جزر مارشال',
        'مارتينيك',
        'موريتانيا',
        ' موريشيوس',
        'مايوت',
        'المكسيك',
        'ميكرونيزيا',
        'مولدوفا ، جمهورية',
        'موناكو',
        'منغوليا',
        'الجبل الأسود',
        'مونتسيرات',
        'المغرب',
        'موزمبيق',
        'ميانمار',
        'ناميبيا',
        'ناورو',
        'نيبال',
        'هولندا',
        'جزر الأنتيل الهولندية',
        'كاليدونيا الجديدة',
        'نيوزيلندا',
        'نيكاراغوا',
        'النيجر',
        'نيجيريا',
        'نيوي',
        'جزيرة نورفولك',
        'جزر مريانا الشمالية',
        'النرويج,',
        'سلطنة عمان',
        'باكستان',
        'بالاو',
        'الأراضي الفلسطينية المحتلة,',
        'بنما',
        'بابوا غينيا الجديدة',
        'باراغواي',
        'بيرو',
        'الفلبين',
        'جزر بيتكيرن',
        'بولندا',
        'البرتغال',
        'بورتوريكو,',
        'دولة قطر',
        'جمع شمل',
        'رومانيا',
        'الاتحاد الروسي',
        'رواندا',
        'ساموا',
        'سان مارينو',
        'سان تومي وبرينسيبي',
        'المملكة العربية السعودية',
        'السنغال',
        'صربيا',
        'سيشيل',
        'سيرا ليون',
        'سنغافورة',
        'سلوفاكيا',
        'سلوفينيا',
        'جزر سليمان',
        'الصومال',
        'جنوب أفريقيا',
        'إسبانيا',
        'سيريلانكا',
        'سانت هيلينا',
        'سانت كيتس ونيفيس',
        'شارع لوسيا',
        'سانت بيير وميكلون',
        'سانت فنسنت وجزر غرينادين',
        'السودان',
        'سورينام',
        'سوازيلاند',
        'السويد',
        'سويسرا',
        'سوريا',
        'تايوان ، جمهورية الصين',
        'طاجيكستان',
        'تنزانيا',
        'تايلاند',
        'تيمور ليشتي',
        'توجو',
        'توكيلاو',
        'تونغا',
        'ترينداد وتوباغو',
        'تونس',
        'ديك رومي',
        '	تركمانستان',
        'جزر تركس وكايكوس',
        'توفالو',
        'أوغندا',
        'أوكرانيا',
        'الإمارات العربية المتحدة',
        'المملكة المتحدة',
        'الولايات المتحدة الامريكية',
        'جزر فيرجن التابعة للولايات المتحدة',
        'أوروغواي',
        'أوزبكستان',
        'فانواتو',
        'مدينة الفاتيكان',
        'فنزويلا',
        'فييت نام',
        'جزر واليس وفوتونا',
        'الصحراء الغربية',
        '	اليمن',
        'زامبيا',
        'زيمبابوي',
      ],
      'language': ['اللغة'],
      'info': ['إحجز'],
      'search': ['البحث', 'كلمة البحث فارغة .. إبدا فى كتابة واحدة الآن'],
      'profile': ['الملف الشخصي', 'اللغه', 'تسجيل الخروج'],
      'auth': [
        'تسجيل الدخول',
        'التسجيل كمستخدم جديد',
        'عمل حساب جديد',
        'نسيت كلمة المرور',
        'الإسم الأول',
        'الإسم الاخير',
        'البريد الإلكتروني',
        'كلمة المرور',
        'أعد كتابة كلمة المرور',
        'هذا الحقل مطلوب',
        'البريد الإلكتروني غير صحيح',
        'كلمه المرور يجب ان تكون 8 حروف على الأقل',
        'كلمة المرور غير متطابقة',
        'أعد تعيين كلمة المرور',
        'هناك مشكلة فى سيرفرنا نحن نعمل الآن على حلها',
        'هناك مشكلة في إتصالك بالإنترنت',
        'تأكد من البريد الإلكترونى وكلمة المرور',
        'تأكد من بريدك الإلكتروني',
        'هذا البريد مستخدم من قبل مستخدم آخر'
      ],
      'checkOut': [
        'الدفع',
        'تفاصيل بطاقة الإئتمان',
        'الإسم الأول',
        'اللقب',
        'معلومات الفواتير',
        'عنوان الشارع',
        'المدينة',
        'الرقم البريدي',
        'الدولة',
        'بيانات الإتصال',
        'البريد الإلكترونى',
        'إدفع الآن',
        'المنطقة',
        'يجب عليك ملأ كل الحقول'
      ],
      'book': [
        'إحجز هذه الرحلة',
        'الرحلة',
        'التاريخ',
        'الركاب',
        'الحجز',
        'راكب',
        'تم',
        'الغاء',
        'مسح',
        'بالغين',
        'اطفال',
        'رضع',
        'عام',
        'يجب إدخال التاريخ وعدد الركاب',
        'هناك مشكلة حدثت حاول مرة اخري',
        'تم الحجز بنجاح',
        'حدد التاريخ'
      ],
      'globals': ['.. إنتظر جاري التحميل'],
      'filter': [
        'التصفيات',
        'المدينة',
        'الميزة',
        'السعر',
        'مجال السعر',
        'التصفية',
        'إزالة التصفية'
      ]
    }
  };

  get langugeCode {
    return _localizedValues[locale.languageCode];
  }

  List<String> get language => langugeCode['language'];
  List<String> get globals => langugeCode['globals'];
  List<String> get book => langugeCode['book'];
  List<String> get checkOut => langugeCode['checkOut'];
  List<String> get countries => langugeCode['countries'];

  List<String> get auth => langugeCode['auth'];

  List<String> get search => langugeCode['search'];
  List<String> get profile => langugeCode['profile'];
  List<String> get filter => langugeCode['filter'];
  List<String> get info => langugeCode['info'];
}
